spring:
  application:
    name: image-upload-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

storage:
  endpoint: ${B2_ENDPOINT:https://s3.eu-central-003.backblazeb2.com}
  region: ${B2_REGION:eu-central-003}
  bucket-name: ${B2_BUCKET_NAME:ci-test-bucket}
  key-id: ${B2_KEY_ID:ci-test-key}
  application-key: ${B2_APPLICATION_KEY:ci-test-application-key}